---
name: kitconcept-intranet-acceptance

services:

  frontend:
    build:
      context: ./frontend
      args:
        - VOLTO_VERSION=${VOLTO_VERSION}
    platform: linux/amd64
    environment:
      RAZZLE_API_PATH: http://localhost:55001/plone
      RAZZLE_INTERNAL_API_PATH: http://backend:55001/plone
    depends_on:
      - backend
    ports:
      - 3000:3000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.acceptance
      args:
        - KC_VERSION=${KC_VERSION}
    platform: linux/amd64
    ports:
      - 55001:55001
