---
name: kitconcept-intranet

services:

  scheduler:
    image: mcuadros/ofelia:latest
    command: daemon --docker -f label=com.docker.compose.project=${COMPOSE_PROJECT_NAME}
    depends_on:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  traefik:
    image: traefik:v3.7

    ports:
      - 80:80

    labels:
      - traefik.enable=true
      - traefik.constraint-label=public

      # GENERIC MIDDLEWARES
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.gzip.compress.excludedcontenttypes=image/png, image/jpeg, font/woff2

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `public`)
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --accesslog
      - --log
      - --api

  frontend:
    image: ghcr.io/kitconcept/kitconcept-intranet-frontend:${RELEASE:-3.0.0a4}
    platform: linux/amd64
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
    depends_on:
      - backend
    labels:
      - traefik.enable=true
      - traefik.constraint-label=public
      # Service
      - traefik.http.services.svc-frontend.loadbalancer.server.port=3000
      # Routers
      ## /
      - traefik.http.routers.rt-frontend.rule=Host(`${STACK_HOSTNAME:-kitconcept-intranet.localhost}`)
      - traefik.http.routers.rt-frontend.entrypoints=http
      - traefik.http.routers.rt-frontend.service=svc-frontend
      - traefik.http.routers.rt-frontend.middlewares=gzip

  backend:
    image: ghcr.io/kitconcept/kitconcept-intranet-backend:${RELEASE:-3.0.0a4}
    platform: linux/amd64
    depends_on:
      - db
      - solr
      - tika
    environment:
      # Site creation
      SITE: Plone
      SITE_SETUP_SOLR: true
      SITE_DEMO_CONTENT: true
      # Runtime configuration
      ZOPE_FORM_MEMORY_LIMIT: 250MB
      HONEYPOT_FIELD: your_email
      # Database configuration
      RELSTORAGE_DSN: >-
        dbname='${DB_NAME:-plone}' user='${DB_USER:-plone}' host='db' password='${DB_PASSWORD:-plone}'
      # Solr configuration
      SOLR_ACTIVATE: true
      COLLECTIVE_SOLR_HOST: solr
      COLLECTIVE_SOLR_PORT: 8983
      COLLECTIVE_SOLR_BASE: /solr/plone
    labels:
      # Ofelia job for backend container
      - "ofelia.enabled=${BACKEND_CLM_ENABLED:-false}"
      - "ofelia.job-exec.datecron.schedule=${BACKEND_CLM_CRONTAB:-0 1 * * *}"
      - "ofelia.job-exec.datecron.command=./docker-entrypoint.sh run scripts/review_reminder.py"

      # Traefik labels for backend container
      - traefik.enable=true
      - traefik.constraint-label=public
      # Services
      - traefik.http.services.svc-backend.loadbalancer.server.port=8080

      # Middlewares
      ## VHM rewrite /++api++/
      - "traefik.http.middlewares.mw-backend-vhm-api.replacepathregex.regex=^/\\+\\+api\\+\\+($$|/.*)"
      - "traefik.http.middlewares.mw-backend-vhm-api.replacepathregex.replacement=/VirtualHostBase/${STACK_PROTOCOL:-http}/${STACK_HOSTNAME:-kitconcept-intranet.localhost}/Plone/++api++/VirtualHostRoot$$1"

      ## VHM rewrite /ClassicUI/
      - "traefik.http.middlewares.mw-backend-vhm-classic.replacepathregex.regex=^/ClassicUI($$|/.*)"
      - "traefik.http.middlewares.mw-backend-vhm-classic.replacepathregex.replacement=/VirtualHostBase/${STACK_PROTOCOL:-http}/${STACK_HOSTNAME:-kitconcept-intranet.localhost}/Plone/VirtualHostRoot/_vh_ClassicUI$$1"


      ## Basic Authentication
      ### Note: all dollar signs in the hash need to be doubled for escaping.
      ### To create user:password pair, it's possible to use this command:
      ### echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
      ### Defaults to admin:admin
      - traefik.http.middlewares.mw-backend-auth.basicauth.users=admin:$$apr1$$uZPT5Fgu$$AmlIdamxT5ipBvPlsdfD70

      # Routers
      - traefik.http.routers.rt-backend-api.rule=Host(`${STACK_HOSTNAME:-kitconcept-intranet.localhost}`) && (PathPrefix(`/++api++`))
      - traefik.http.routers.rt-backend-api.entrypoints=http
      - traefik.http.routers.rt-backend-api.service=svc-backend
      - traefik.http.routers.rt-backend-api.middlewares=gzip,mw-backend-vhm-api
      ## /ClassicUI
      - traefik.http.routers.rt-backend-classic.rule=Host(`${STACK_HOSTNAME:-kitconcept-intranet.localhost}`) && PathPrefix(`/ClassicUI`)
      - traefik.http.routers.rt-backend-classic.entrypoints=http
      - traefik.http.routers.rt-backend-classic.service=svc-backend
      - traefik.http.routers.rt-backend-classic.middlewares=gzip,mw-backend-auth,mw-backend-vhm-classic
      ## admin
      - traefik.http.routers.rt-backend-admin.rule=Host(`admin.${STACK_HOSTNAME:-kitconcept-intranet.localhost}`)
      - traefik.http.routers.rt-backend-admin.entrypoints=http
      - traefik.http.routers.rt-backend-admin.service=svc-backend
      - traefik.http.routers.rt-backend-admin.middlewares=gzip,mw-backend-auth

  db:
    image: postgres:${DB_VERSION:-18}
    environment:
      POSTGRES_USER: ${DB_USER:-plone}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-plone}
      POSTGRES_DB: ${DB_NAME:-plone}
    volumes:
      - vol-db-data:/var/lib/postgresql

  tika:
    image: apache/tika:${TIKA_TAG:-3.2.3.0-full}
    platform: linux/amd64

  solr:
    image: ghcr.io/kitconcept/solr:${SOLR_TAG:-3.0.0a2}
    platform: linux/amd64
    command:
      - solr-precreate
      - plone
      - /plone-config
    environment:
      SOLR_MODULES: extraction
      SOLR_OPTS: "-Dsolr.tika.url=http://tika:9998"

volumes:
  vol-db-data: {}