[project]
name = "kitconcept-intranet-docs"
description = "The kitconcept Intranet distribution documentation."
keywords = [
    "kitconcept",
    "intranet",
    "distribution",
    "documentation",
    "Plone",
    "Diátaxis",
]
version="1.0.0"
readme = "README.md"
requires-python = "==3.14.*"
license = { file = "LICENSE" }
maintainers = [
    { name = "kitconcept", email = "info@kitconcept.com" },
]
authors = [
    { name = "kitconcept", email = "info@kitconcept.com" },
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
]

dependencies = [
    "kitconcept-intranet",
    "kitconcept-voltolighttheme>=8.0.0a30",
]

[dependency-groups]
dev = [
    "graphviz",
    "linkify-it-py",
    "myst-parser",
    "plone-sphinx-theme",
    "sphinx-autobuild",
    "sphinx-copybutton",
    "sphinx-design",
    "sphinx-examples",
    "sphinx-notfound-page",
    "sphinx-reredirects",
    "sphinx-sitemap",
    "sphinx-tippy",
    "sphinxcontrib-httpdomain",
    "sphinxcontrib-httpexample",
    "sphinxcontrib-mermaid",
    "sphinxext-opengraph",
    "vale",
]

[project.urls]
Repository = "https://github.com/kitconcept/kitconcept.intranet"
Documentation = "https://kitconcept.github.io/kitconcept.intranet/"

[tool.uv.sources]
kitconcept-intranet = { path = "../backend/", editable = true }
