name: "kitconcept.intranet: CI"
description: "Main workflow for kitconcept.intranet"

on:
  push:
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/backend.yml"
      - ".github/workflows/frontend.yml"
      - ".github/workflows/main.yml"
      - "devops/**"
  workflow_dispatch:

jobs:

  config:
    name: "Config: Compute values used in workflow"
    uses: ./.github/workflows/config.yml

  backend:
    uses: ./.github/workflows/backend.yml
    needs:
        - config
    with:
        base-tag: ${{ needs.config.outputs.base-tag }}
        image-name-prefix: ${{ needs.config.outputs.image-name-prefix }}
        image-name-suffix: backend
        python-version: ${{ needs.config.outputs.python-version }}
        kc-version: ${{ needs.config.outputs.kc-version }}
    if: ${{ needs.config.outputs.backend == 'true' }}
    permissions:
      contents: read
      packages: write

  frontend:
    uses: ./.github/workflows/frontend.yml
    needs:
        - config
    with:
        base-tag: ${{ needs.config.outputs.base-tag }}
        image-name-prefix: ${{ needs.config.outputs.image-name-prefix }}
        image-name-suffix: frontend
        node-version: ${{ needs.config.outputs.node-version }}
        volto-version: ${{ needs.config.outputs.volto-version }}
    if: ${{ needs.config.outputs.frontend == 'true' }}
    permissions:
      contents: read
      packages: write

  acceptance:
    name: "Acceptance: ${{ matrix.name }}"
    if: ${{ needs.config.outputs.acceptance == 'true' && (always() && !contains(needs.*.result, 'failure'))}}
    uses: ./.github/workflows/acceptance.yml
    needs:
      - config
      - backend
      - frontend
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Main"
            short-name: main
          - name: "Core - Basic"
            short-name: core/basic
          - name: "Core - Blocks"
            short-name: core/blocks
          - name: "Core - Content"
            short-name: core/content
          - name: "a11y"
            short-name: a11y
            a11y: true
    with:
      name: ${{ matrix.name }}
      short-name: ${{ matrix.short-name }}
      node-version: ${{ needs.config.outputs.node-version }}
      image-name-prefix: ${{ needs.config.outputs.image-name-prefix }}
      image-tag: ${{ needs.config.outputs.base-tag }}
      a11y: ${{ matrix.a11y || false }}
